CREATE TABLE Questions(
Id INT PRIMARY KEY IDENTITY(1,1),
Title NVARCHAR(MAX),
[Description] NVARCHAR(MAX),
CategoryId INT FOREIGN KEY REFERENCES Categories(Id),
UserId NVARCHAR(450) FOREIGN KEY REFERENCES AspNetUsers(Id),
CreatedOn DATETIME NULL);

CREATE TRIGGER  
Inserts ON Questions FOR 
INSERT AS 
UPDATE Questions
SET CreatedOn=GETDATE();
